customer:
  create:
    method: post
    url: '/foo/bar'

  has_domain_ownership:
    method: post
    url: '/foo/bar'

tenant:
  exists:
    method: post
    url: '/foo/bar'

order:
  license_create:
    method: post
    url: '/order/cloud/license'

contact:
  create:
    method: post
    url: '/foo/bar'

addon:
  create:
    method: post
    url: '/foo/bar'

terminate:
  order:
    method: post
    url: '/foo/bar'
